/**
 * PM2 ecosystem for Archaser backend deploy hosts.
 * Frontend Next apps still start from deploy root via `npm --prefix frontend start`
 * (or a separate frontend ecosystem when repos are split).
 *
 * Env: load from `backend/.env` on the host (copied from .env.production / .env.staging).
 */
module.exports = {
    apps: [
        {
            name: "archaser-main",
            cwd: "/home/ubuntu/production",
            script: "npm",
            args: "--prefix frontend start",
            env: {
                NODE_ENV: "production",
                PORT: 3000,
                ENABLE_LOKI_LOGGING: "true",
                LOKI_HOST: "http://localhost:3100",
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "1G",
            min_uptime: "10s",
            max_restarts: 10,
            restart_delay: 4000,
            exp_backoff_restart_delay: 100,
            kill_timeout: 5000,
            wait_ready: true,
            listen_timeout: 10000,
            error_file: "/home/ubuntu/logs/archaser-main-error.log",
            out_file: "/home/ubuntu/logs/archaser-main-out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            time: true,
        },
        {
            name: "archaser-staging",
            cwd: "/home/ubuntu/staging",
            script: "npm",
            args: "--prefix frontend start",
            env: {
                NODE_ENV: "production",
                PORT: 3001,
                ENABLE_LOKI_LOGGING: "true",
                LOKI_HOST: "http://localhost:3100",
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "1G",
            min_uptime: "10s",
            max_restarts: 10,
            restart_delay: 4000,
            exp_backoff_restart_delay: 100,
            kill_timeout: 5000,
            wait_ready: true,
            listen_timeout: 10000,
            error_file: "/home/ubuntu/logs/archaser-staging-error.log",
            out_file: "/home/ubuntu/logs/archaser-staging-out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            time: true,
        },
        {
            name: "archaser-monitoring",
            cwd: "/home/ubuntu/production",
            script: "docker",
            // Compose + Grafana stack live under backend/grafana; env from backend/.env
            args: "compose --env-file backend/.env -f backend/grafana/docker-compose.logging.yml up",
            env: {
                MONITORING_ENV: "production",
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "1G",
            min_uptime: "10s",
            max_restarts: 10,
            restart_delay: 4000,
            exp_backoff_restart_delay: 100,
            kill_timeout: 5000,
            error_file: "/home/ubuntu/logs/archaser-monitoring-error.log",
            out_file: "/home/ubuntu/logs/archaser-monitoring-out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            time: true,
        },
        {
            name: "archaser-website",
            cwd: "/home/ubuntu/website",
            script: "npm",
            args: "start",
            env: {
                NODE_ENV: "production",
                PORT: 4000,
                ENABLE_LOKI_LOGGING: "true",
                LOKI_HOST: "http://localhost:3100",
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "1G",
            min_uptime: "10s",
            max_restarts: 10,
            restart_delay: 4000,
            exp_backoff_restart_delay: 100,
            kill_timeout: 5000,
            error_file: "/home/ubuntu/logs/archaser-website-error.log",
            out_file: "/home/ubuntu/logs/archaser-website-out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            time: true,
        },
        {
            name: "archaser-api",
            cwd: "/home/ubuntu/production",
            script: "docker",
            args: "compose --project-name archaser-backend --env-file backend/.env -f backend/docker-compose.backend.production.yml up --remove-orphans",
            env: {
                NODE_ENV: "production",
                NEST_PORT: 3010,
                PORT: 3010,
                ENABLE_LOKI_LOGGING: "true",
                LOKI_HOST: "http://localhost:3100",
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "1G",
            min_uptime: "10s",
            max_restarts: 10,
            restart_delay: 4000,
            exp_backoff_restart_delay: 100,
            kill_timeout: 5000,
            wait_ready: true,
            listen_timeout: 10000,
            error_file: "/home/ubuntu/logs/archaser-api-error.log",
            out_file: "/home/ubuntu/logs/archaser-api-out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            time: true,
        },
        {
            name: "archaser-api-staging",
            cwd: "/home/ubuntu/staging",
            script: "docker",
            args: "compose --project-name archaser-backend-staging --env-file backend/.env -f backend/docker-compose.backend.staging.yml up --remove-orphans",
            env: {
                NODE_ENV: "production",
                NEST_PORT: 3010,
                PORT: 3010,
                SERVICE_NAME: "archaser-api-staging",
                ENABLE_LOKI_LOGGING: "true",
                LOKI_HOST: "http://localhost:3100",
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "1G",
            min_uptime: "10s",
            max_restarts: 10,
            restart_delay: 4000,
            exp_backoff_restart_delay: 100,
            kill_timeout: 5000,
            wait_ready: true,
            listen_timeout: 10000,
            error_file: "/home/ubuntu/logs/archaser-api-staging-error.log",
            out_file: "/home/ubuntu/logs/archaser-api-staging-out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            time: true,
        },
    ],
};
