/**
 * PM2 ecosystem for Archaser backend deploy hosts.
 *
 * Env: load from `backend/.env` on the host (copied from .env.production / .env.staging).
 */
module.exports = {
    apps: [
        {
            name: "archaser-api",
            cwd: "/home/ubuntu/api",
            script: "node",
            args: "dist/main.js",
            env: {
                NODE_ENV: "production",
                NEST_PORT: 3010,
                PORT: 3010,
                ENABLE_LOKI_LOGGING: "true",
                LOKI_HOST: "http://localhost:3100",
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "1G",
            min_uptime: "10s",
            max_restarts: 10,
            restart_delay: 4000,
            exp_backoff_restart_delay: 100,
            kill_timeout: 5000,
            wait_ready: true,
            listen_timeout: 10000,
            error_file: "/home/ubuntu/logs/archaser-api-error.log",
            out_file: "/home/ubuntu/logs/archaser-api-out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            time: true,
        },
        {
            name: "archaser-monitoring",
            cwd: "/home/ubuntu/production",
            script: "docker",
            args: "compose --env-file backend/.env -f backend/grafana/docker-compose.logging.yml up",
            env: {
                MONITORING_ENV: "production",
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "1G",
            min_uptime: "10s",
            max_restarts: 10,
            restart_delay: 4000,
            exp_backoff_restart_delay: 100,
            kill_timeout: 5000,
            error_file: "/home/ubuntu/logs/archaser-monitoring-error.log",
            out_file: "/home/ubuntu/logs/archaser-monitoring-out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            time: true,
        },
        {
            name: "archaser-website",
            cwd: "/home/ubuntu/website",
            script: "npm",
            args: "start",
            env: {
                NODE_ENV: "production",
                PORT: 4000,
                ENABLE_LOKI_LOGGING: "true",
                LOKI_HOST: "http://localhost:3100",
            },
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "1G",
            min_uptime: "10s",
            max_restarts: 10,
            restart_delay: 4000,
            exp_backoff_restart_delay: 100,
            kill_timeout: 5000,
            error_file: "/home/ubuntu/logs/archaser-website-error.log",
            out_file: "/home/ubuntu/logs/archaser-website-out.log",
            log_date_format: "YYYY-MM-DD HH:mm:ss Z",
            merge_logs: true,
            time: true,
        },
    ],
};
