#!/usr/bin/env python3
"""Render Grafana MongoDB datasource YAML from MONGODB_URI.

Database name is taken from the URI path (…/dbname?…), not from a separate
MONGODB_DATABASE env var. Writes provisioning YAML for haohanyang-mongodb-datasource.

No third-party deps (stdlib only).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse

OUT = Path(__file__).resolve().parent.parent / "provisioning" / "datasources" / "mongodb.generated.yaml"
PLUGIN_TYPE = "haohanyang-mongodb-datasource"
DATASOURCE_UID = "MongoDB"
DATASOURCE_NAME = "MongoDB"


def yaml_str(value: str) -> str:
    """Double-quote a YAML string (safe for passwords / special chars)."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def parse_mongodb_uri(uri: str) -> dict[str, str]:
    if not uri or not uri.strip():
        raise ValueError("MONGODB_URI is empty")

    raw = uri.strip().strip('"').strip("'")
    if raw.startswith("mongodb+srv://"):
        scheme = "mongodb+srv"
        normalized = "https://" + raw[len("mongodb+srv://") :]
    elif raw.startswith("mongodb://"):
        scheme = "mongodb"
        normalized = "http://" + raw[len("mongodb://") :]
    else:
        raise ValueError("MONGODB_URI must start with mongodb:// or mongodb+srv://")

    parsed = urlparse(normalized)
    if not parsed.hostname:
        raise ValueError("MONGODB_URI is missing host")

    database = unquote(parsed.path.lstrip("/").split("/")[0]) if parsed.path else ""
    if not database:
        raise ValueError(
            "MONGODB_URI has no database path (expected …/dbname?…). "
            "Update the URI path to the DB Grafana should query."
        )

    host = parsed.hostname
    if scheme == "mongodb" and parsed.port:
        host = f"{host}:{parsed.port}"

    username = unquote(parsed.username) if parsed.username else ""
    password = unquote(parsed.password) if parsed.password else ""

    return {
        "scheme": scheme,
        "host": host,
        "database": database,
        "username": username,
        "password": password,
        "connection_options": parsed.query or "",
    }


def write_file(body: str) -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")


def write_disabled(reason: str) -> None:
    body = f"""# Auto-generated by grafana/scripts/render-mongodb-datasource.py
# MongoDB datasource disabled: {reason}
apiVersion: 1
deleteDatasources:
  - name: {DATASOURCE_NAME}
    orgId: 1
datasources: []
"""
    write_file(body)
    print(f"[grafana-mongo] wrote disabled datasource → {OUT} ({reason})")


def write_enabled(parts: dict[str, str]) -> None:
    lines = [
        "# Auto-generated by grafana/scripts/render-mongodb-datasource.py — do not edit.",
        f"# database={parts['database']} host={parts['host']} scheme={parts['scheme']}",
        "apiVersion: 1",
        "deleteDatasources:",
        f"  - name: {DATASOURCE_NAME}",
        "    orgId: 1",
        "datasources:",
        f"  - name: {DATASOURCE_NAME}",
        f"    type: {PLUGIN_TYPE}",
        f"    uid: {DATASOURCE_UID}",
        "    access: proxy",
        "    orgId: 1",
        "    isDefault: false",
        "    editable: false",
        "    jsonData:",
        f"      connectionStringScheme: {yaml_str(parts['scheme'])}",
        f"      host: {yaml_str(parts['host'])}",
        f"      database: {yaml_str(parts['database'])}",
        f"      connectionOptions: {yaml_str(parts['connection_options'])}",
    ]
    if parts["username"] and parts["password"]:
        lines.append('      authType: "username-password"')
        lines.append(f"      username: {yaml_str(parts['username'])}")
        lines.append("    secureJsonData:")
        lines.append(f"      password: {yaml_str(parts['password'])}")
    else:
        lines.append('      authType: ""')
        lines.append("    secureJsonData: {}")

    write_file("\n".join(lines) + "\n")
    print(
        f"[grafana-mongo] provisioned MongoDB datasource database={parts['database']} "
        f"host={parts['host']} → {OUT}"
    )


def load_mongodb_uri_from_env_file(path: str) -> str | None:
    """Read MONGODB_URI from a dotenv file without shell-sourcing secrets."""
    try:
        text = Path(path).read_text(encoding="utf-8")
    except OSError as err:
        print(f"[grafana-mongo] cannot read env file {path}: {err}", file=sys.stderr)
        return None

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        if key.strip() != "MONGODB_URI":
            continue
        value = value.strip()
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]
        return value
    return None


def main(argv: list[str]) -> int:
    env_file: str | None = None
    if len(argv) >= 3 and argv[1] == "--env-file":
        env_file = argv[2]

    uri = os.environ.get("MONGODB_URI", "").strip()
    if not uri and env_file:
        loaded = load_mongodb_uri_from_env_file(env_file)
        if loaded:
            uri = loaded.strip()

    if not uri:
        write_disabled("MONGODB_URI not set")
        return 0

    try:
        parts = parse_mongodb_uri(uri)
    except ValueError as err:
        print(f"[grafana-mongo] error: {err}", file=sys.stderr)
        write_disabled(str(err))
        return 1

    write_enabled(parts)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
