-- Optional: register daily job for computeCustomerOverdueMetrics (cronManager case name must match exactly).
-- Adjust sort_order and cron_expression to match your scheduler expectations.
--
-- INSERT INTO "CronJob" (
--   name,
--   active,
--   cron_expression,
--   sort_order,
--   timeout_period_seconds
-- )
-- SELECT
--   'Compute Customer Overdue Metrics',
--   true,
--   '0 2 * * *',
--   COALESCE((SELECT MAX(sort_order) + 1 FROM "CronJob"), 1),
--   3600
-- WHERE NOT EXISTS (
--   SELECT 1 FROM "CronJob" WHERE name = 'Compute Customer Overdue Metrics'
-- );
